### ISSUE TITLE
Home Assistant Add-on

### ISSUE THREAD

**Issue by supersebbo** [jshank/bwalink#10]
Hi,

Very excited to start experimenting with this project for my Balboa BP2100 based spa, my Elfin-EW11A is on order.   I wondered, did you ever consider publishing this as an all-in-one Home Assistant 'add-on'?  Add-ons are simply docker containers with a bit of meta-data to allow HA to manage them, it also allows for easy integration wtih HA hosted MQTT servers with HA managing credentials.  I think it could almost fully automate the installation process for this system - all people would need to do is configure the Elfin. 

If so or not, I'd be interested in helping/partnering on this.  Let me know. 

Thanks!

**Comment by jshank** [comment]
It's a great idea but unfortunately, I'm not the author of the https://github.com/ccutrer/balboa_worldwide_app module. My contribution and this repository is just a docker wrapper around @ccutrer amazing code with a few additions to support the Elfin adapter. You should ask the same on his repo. I'd be happy to contribute anything here to the effort.

**Comment by jshank** [comment]
Saw your post over on Cody's repository. Looks great. Feel free to use anything here and thanks for continuing the work.
