### ISSUE TITLE
Host is unreachable

### ISSUE THREAD

**Issue by davidjac** [jshank/bwalink#13]
THis had been running fine for three days and suddenly after a start it immediately stops. Does it perhaps mean that Balboa server is down? 

Heres the log:

[08:20:51] INFO: Starting BWALink addon...
[08:20:52] INFO: Setting addon timezone to Europe/London based on the system timezone.
[08:20:52] INFO: Starting mqtt bridge connecting tcp://192.168.0.16:8899/ to mqtt://core-mosquitto:1883
/usr/lib/ruby/gems/3.2.0/gems/balboa_worldwide_app-2.1.5/lib/bwa/client.rb:42:in `initialize': Host is unreachable - connect(2) for "192.168.0.16" port 8899 (Errno::EHOSTUNREACH)
	from /usr/lib/ruby/gems/3.2.0/gems/balboa_worldwide_app-2.1.5/lib/bwa/client.rb:42:in `new'
	from /usr/lib/ruby/gems/3.2.0/gems/balboa_worldwide_app-2.1.5/lib/bwa/client.rb:42:in `initialize'
	from /usr/lib/ruby/gems/3.2.0/gems/balboa_worldwide_app-2.1.5/exe/bwa_mqtt_bridge:416:in `new'
	from /usr/lib/ruby/gems/3.2.0/gems/balboa_worldwide_app-2.1.5/exe/bwa_mqtt_bridge:416:in `<top (required)>'
	from /usr/bin/bwa_mqtt_bridge:25:in `load'
	from /usr/bin/bwa_mqtt_bridge:25:in `<main>'

**Comment by GemacFPV** [comment]
Hey can you share your bwa_mqtt_bridge.service file ? It seems like i have the same setup but something is not right...

[Unit]
Description=Balboa Spa MQTT Bridge

[Service]
User=root
ExecStart=/usr/local/bin/bwa_mqtt_bridge mqtt://homeassistant:123456789@localhost:1883/ tcp://192.168.178.118:8899/
Environment="LOG_LEVEL=WARN" "LOG_VERBOSITY=0"
Restart=always
RestartSec=3s
Type=notify
NotifyAccess=main
WatchdogSec=60

[Install]
WantedBy=multi-user.target
