### ISSUE TITLE
Initial Start of BWALink is hanging

### ISSUE THREAD

**Issue by jlogan223** [jshank/bwalink#14]
Hi, I have installed the Addon BWALink, updated the config file to have the Bridge IP ( assuming this is the IP for the EW11), left the bridge port as default ( 8899), and not touched any other settings.  I then hit save and start the Addon. My Log File just sits like this:
```

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[19:00:38] INFO: Starting BWALink addon...
[19:00:38] INFO: Setting addon timezone to Europe/London based on the system timezone.
[19:00:38] INFO: Starting mqtt bridge connecting tcp://192.168.2.13:8899/ to mqtt://core-mosquitto:1883
I,   to spa: #<BWA::Messages::ConfigurationRequest>
D, wrote: 7e 05 0a bf 04 77 7e
```

Have I done something wrong?

**Comment by jlogan223** [comment]
Hi @jshank, Any idea what I could have done wrong?
Thanks.

**Comment by jshank** [comment]
Apologies for the delay @jlogan223 - Did you solve this?

**Comment by jlogan223** [comment]
Hi Jim,

No worries. Yes I did thanks. I made the silly assumption that even if the ew11 wasn't connected to the hottub but just powred up, that it would still show up as a stand alone device in MQTT. However, that isn't the case. It needs to be sending some data for it to be picked up by MQTT. Once I connected it to the hottub, it sprang in to life.

This is a great bit of work you have done. Thank you so much. 🙌

________________________________

**Comment by jshank** [comment]
You bet, thanks for sharing your experience, it helps other who may run into the same issue.
