### ISSUE TITLE
Warnings - lots of logs about entity names

### ISSUE THREAD

**Issue by erikbjork** [jshank/bwalink#17]
When Home Assistant starts, it logs a lot of warnings about entity names from BWA Link. Names should not start with the device name.

`2024-02-04 07:49:02.840 WARNING (MainThread) [homeassistant.components.mqtt.mixins] MQTT entity name starts with the device name in your config {'name': 'BWA Link Filter Cycle 2 Duration', 'availability_topic': 'homie/bwa/$state', 'payload_available': 'ready', 'payload_not_available': 'lost', 'qos': 1, 'icon': 'mdi:clock', 'device': {'manufacturer': 'Balboa Water Group', 'sw_version': '2.1.4', 'model': 'BP200UX', 'name': 'BWA Link', 'identifiers': ['bwa'], 'connections': []}, 'state_topic': 'homie/bwa/filter-cycle2/duration', 'command_topic': 'homie/bwa/filter-cycle2/duration/set', 'command_template': Template<template=({{ value | round(0) }}) renders=0>, 'unit_of_measurement': 'minutes', 'min': 0.0, 'max': 1439.0, 'unique_id': 'bwa_filter-cycle2_duration', 'availability_mode': 'latest', 'mode': <NumberMode.AUTO: 'auto'>, 'retain': False, 'payload_reset': 'None', 'enabled_by_default': True, 'optimistic': False, 'step': 1.0, 'encoding': 'utf-8'}, this is not expected. Please correct your configuration. The device name prefix will be stripped off the entity name and becomes 'Filter Cycle 2 Duration'`

This has been fixed in https://github.com/ccutrer/balboa_worldwide_app, adressed in this issue: https://github.com/ccutrer/balboa_worldwide_app/issues/76. 

**Please address this issue by building a new version of this container image to update balboa_worldwide_app.**

**Comment by jshank** [comment]
Should be fixed in 2024.02. Please test and let me know.

**Comment by erikbjork** [comment]
Wow! That was a quick response! ⭐ 

I can confirm that the warnings are now gone. Thank you!

**Comment by jshank** [comment]
You bet, thanks for the heads up on the fix @erikbjork. Took me a minute to remember how to push a release. I am not a developed though I play one on the internet ;)
