### ISSUE TITLE
Unknown error, see supervisor

### ISSUE THREAD

**Issue by lempparisi** [jshank/bwalink#20]
Hi,

I have a problem installing this as an add-on into my Home Assistant.

I copied all the files from ha-addon folder as shown here: ( They are located in /addons/bwalink/...)
![image](https://github.com/jshank/bwalink/assets/17859259/78024eb5-8635-47d8-8802-5a540a4d302e)

After this I found the add-on in Home assistant add-on settings as it should be.

I tried to click install and I got this error message:
![image](https://github.com/jshank/bwalink/assets/17859259/38237299-a8ba-4027-8766-56dda95c483a)

I checked the home assistant log file and it tells following error:
ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/local_bwalink/install - Unknown error, see supervisor

I think it is missing files in that ha-addon file or then it is something else?
Can you help?

**Comment by jshank** [comment]
I think you have the wrong repository. The add-on is from https://github.com/supersebbo/bwa-mqtt-bridge-addon

**Comment by lempparisi** [comment]
I did exactly like it says here:
https://github.com/supersebbo/bwa-mqtt-bridge-addon/wiki/Installation-&-Run

Still getting the same error:
Failed to install add-on
Unknown error, see supervisor

And the HA Log says about the same:
2024-05-19 21:37:48.765 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/local_bwa_mqtt_bridge/install - Unknown error, see supervisor


I also tried this:
"Tutorial: Making your first add-on"

I'm getting the same error... maybe this a hardware issue or something else?

My HA is running on old Intel NUC pc.. I installed HA on a fresh hard drive and use it as OS for the NUC.

**Comment by Latee32** [comment]
Did you guys get this work?
I get the same error.. and i dont know whats wrong, i tried both repositories..
