### ISSUE TITLE
No data published to MQTT

### ISSUE THREAD

**Issue by wieshka** [jshank/bwalink#23]
Hi,

Spent already a while to figure out this, but without luck.
The situation:
- MQTT broker running on HA;
- BWALink Addon running with output:
```
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[21:40:17] INFO: Starting BWALink addon...
[21:40:17] INFO: Setting addon timezone to Europe/Riga based on the system timezone.
[21:40:17] INFO: Starting mqtt bridge connecting tcp://192.168.50.126:8899/ to mqtt://core-mosquitto:1883
I,   to spa: #<BWA::Messages::ConfigurationRequest>
D, wrote: 7e 05 0a bf 04 77 7e
```
- Elfin EW11 running, RS485 A/B pins connected to alternate port to Topside panel according to wiring schematics. Power from external DC. 
- Elfin reports frames received every second, hence I assume RS485 data transmission is happening;
Serial Port State
Received Bytes
1430016
Received Frames
2793
Config
115200,8,1,NONE
- Board: Balboa BP200UX

**Comment by wieshka** [comment]
Came across #14, but in my case Elfin is connected, and Received bytes/frames suggest data are flowing in.

**Comment by jshank** [comment]
Thanks for raising https://github.com/ccutrer/balboa_worldwide_app/issues/87. That's likely the best place to get help. It's  unlikely the issue is related to the docker containerization.
