### ISSUE TITLE
Power the serial to ip bridge

### ISSUE THREAD

**Issue by magma1447** [jshank/bwalink#7]
Hi. Thank you for providing this, it seems awesome. I am planning to shop some stuff to make this possible for me. But I have one question that I didn't see covered.

Is there enough juice in the serial connector to power the `Elfin-EW11A-0`? I see that it requires 5W. Or are you using another power source? It would be neat to not have to add 5V myself.

**Comment by jshank** [comment]
Indeed there is enough power from the RS485 connection to power the Elfin-EW11A-0 directly from the board. No need for an external power supply or DC-DC inverter.
