### ISSUE TITLE
Not an issue as such

### ISSUE THREAD

**Issue by funks81** [jshank/bwalink#8]
Sorry - I know this isn't really the correct place for this - but asking to be pointed in the correct direction.  Very new to Home Assistant and currently running inside Virtualbox on a 2008 iMac.  Have managed to attach the Elfin EW11a to my hot tub and joined my home wifi.

I'm struggling with the docker stuff - as my computer is too old to install docker.  Can anyone point me in the right direction for some kind of work around for this?  Would need to be spelt out fairly simply!!

Thanks in advance

**Comment by jshank** [comment]
Ooof, that's going to be tough @funks81. This docker container removes the complexity of setting up a properly working Ruby environment along with a virtual-port that represents your tubs controller. If you really want to do it on your existing hardware, try this:
- Get [homebrew](https://brew.sh/) installed on your iMac 
- [install Ruby](https://www.ruby-lang.org/en/documentation/installation/#homebrew). 
- Install the [balboa_worldwide_app](https://github.com/ccutrer/balboa_worldwide_app#mqtthomie-bridge)
- Install socat to get the virtual port using `brew install socat` 
- Run socat, then balboa_worldwide_app. Look at my [docker-entrypoint.sh](https://github.com/jshank/bwalink/blob/main/docker-entrypoint.sh) for example on the commands
- Find some way to automate their startup on reboot or just remember to start them each time your iMac starts

Beyond that, you are going to need an MQTT broker but I think there is already a [Home Assistant module](https://github.com/home-assistant/addons/blob/master/mosquitto/DOCS.md) to do that.

As a beginner you'll learn a lot by doing it that way but it's going to be a long and possibly frustrating road. It may be far easier to get your hands on some newer hardware, an Intel NUC or similar and set up a proper Ubuntu/Docker host.

**Comment by funks81** [comment]
Many thanks for this - sounds like this may be a little beyond me!!!  I think maybe the purchase of some new hardware may save a lot of time and effort.
